jobs:
# Configure, build, install, and test job
- job: 'linux_build'
  displayName: 'Linux Builds'
  pool:
    vmImage: 'ubuntu-16.04'
  timeoutInMinutes: 120
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
  strategy:
    maxParallel: 8
    matrix:
      gcc_build:
        CXX_COMPILER: 'g++'
        PYTHON_VER: '3.7'
        C_COMPILER: 'gcc'
        F_COMPILER: 'gfortran'
        BUILD_TYPE: 'release'

  steps:
  - bash: |
      uname -a
      free -m
      df -h
      ulimit -a
    displayName: "Hardware Information"

  - bash: |
      sudo apt-get update
      sudo apt-get install gfortran
    displayName: "Install gFortran"

  - bash: |
        echo "##vso[task.prependpath]$CONDA/bin"
        conda config --set always_yes yes
    displayName: "Add conda to PATH"

  - bash: |
      conda create -q -n p4env python=$PYTHON_VER psi4 --only-deps -c psi4/label/dev
      source activate p4env
      which python
      conda install \
        dftd3 \
        gcp \
        resp \
        pycppe \
        pylibefp \
        snsmp2 \
        mp2d \
        pytest-xdist \
        -c psi4/label/dev
      conda install \
        blas=*=mkl \
        mkl-include \
        qcelemental \
        qcengine \
        pybind11 \
        -c conda-forge
      conda list
    displayName: 'Build Environment'

  - bash: |
      source activate p4env
      python -V
      python -c 'import numpy; print(numpy.version.version)'
      export CXX=${CXX_COMPILER}
      export CC=${C_COMPILER}
      export FC=${F_COMPILER}
      ${CXX_COMPILER} --version
      ${F_COMPILER} --version
      ${C_COMPILER} --version
      # * can't use conda dist of the more complicated lib pkgs (e.g., CheMPS2, PCMSolver, v2rdm)
      #   b/c their c++ symbols don't mix with the different Travis compilers. for other
      #   reasons, pkgs are being compiled less statically, sad for CI.
      # * can't enable trivial plugins b/c no psi4 for them to detect at start (e.g., snsmp2)
      cmake -Bbuild -H. \
        -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
        -DCMAKE_C_COMPILER=${C_COMPILER} \
        -DCMAKE_Fortran_COMPILER=${F_COMPILER} \
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -DCMAKE_PREFIX_PATH=${CONDA}/envs/p4env \
        -DPYTHON_EXECUTABLE="${CONDA}/envs/p4env/bin/python" \
        -DENABLE_CheMPS2=OFF \
        -DENABLE_dkh=ON \
        -DENABLE_libefp=ON \
        -DENABLE_erd=OFF \
        -DENABLE_gdma=ON \
        -DENABLE_PCMSolver=OFF \
        -DENABLE_simint=ON \
        -DENABLE_snsmp2=OFF \
        -DENABLE_v2rdm_casscf=OFF \
        -DENABLE_PLUGIN_TESTING=ON \
        -DCMAKE_INSTALL_PREFIX=$(Agent.BuildDirectory)/Install
    displayName: 'Configure Build'

  - bash: |
      cd build
      source activate p4env
      ../.scripts/travis_build.sh
    displayName: 'Build Psi4'

  - bash: |
      cd build
      source activate p4env
      ./stage/bin/psi4 ../tests/tu1-h2o-energy/input.dat
    displayName: 'Spot Test'

  - bash: |
      cd build
      source activate p4env
      python ../.scripts/travis_run_test.py
      python ../.scripts/travis_print_failing.py
    displayName: 'CTest Tests'

  - bash: |
      cd build
      source activate p4env
      PYTHONPATH=stage/lib/ pytest -v -rws --durations=15 -n 2 -m 'quick' stage/lib/psi4/tests/
    displayName: 'PyTest Tests'
